from: markdown-emoji
to: html

toc: true
number-sections: true
input-file: markdown.md
output-file: index.html

metadata:
  title: My title

template: ${.}/templates/template.html
css: ./styles/theme.css
